---
title: "Creative Writing is Experiential Learning!"
author: "Christopher R. H. Hanusa"
date: 2015-11-02
categories:
  - "teaching"
description: "Abstract: Creative writing gives students a chance to experience a topic in a new way and lets students try on an alternate persona. Also, I muse..."
---

**Abstract:** Creative writing gives students a chance to experience a topic in a new way and lets students try on an alternate persona.  Also, I muse about how to include creative writing in a math class.

At the [Experiential Learning Lunch](../2015-10-26-experiential-learning-lunch-on-21-oct-2015/index.qmd) on October 21, 2015, we had a lively discussion about creative writing and why it is such a powerful tool in experiential learning.

Keren Dali (Library and Information Science) explained that creative writing is a great way to inject energy into the classroom.  She has students choose from writing a screenplay, a letter to the editor, a blog post, a love story, etc.  It allows the students to change their voice by playing a role, which allows students to take risks that they wouldn't take from their usual position.  For example, a student might learn about the background of an author and do some reflective writing about them.  This would help the student to connect better with the author's writing because the students place themselves in the author's shoes.

Yves Cloarec (English) voiced the concern that standard writing assignments often have the students writing what they think the instructor wants to hear.  An example was given in which students did background work or research that supports one conclusion and they write that it supports an opposing conclusion because that is what they think is what the research was supposed to say!

Yves also talked about the process he uses to have the students get the most out of their creative writing.  His assignments often have two parts.  There is the creative writing part, but there is also an academic writing part.  For every two pages of creative writing that the students submit, they are also expected to produce one page of academic writing explaining the thought process behind their creative writing.  The students would discuss the research that went into their work, giving citations for theoretical resources or showing analogous constructions in other works they have read.  This left a strong impression on me because I often think of "creative writing" as something that is difficult to grade objectively and fuzzy in some sense, but by requiring students to theoretically justify their creativity, you can see the thought process behind the project, and see that the students actually put thought into their work.

There was a discussion about having students learn about the writing process by having the students first think about all the steps involved in making toast---it sounds easy until you go into all the steps.  The students are asked not to write the steps but instead use symbols to draw the steps of the process.  Once the students have tripped over themselves they are supposed to learn that writing is a process as well.  That writing entails first thinking about what they want to write, organizing their thoughts, starting to write, and rewriting (multiple times).

This exercise made me think about a recent blog post that I read about teaching students how to write mathematical proofs, where every step from start to finish must be explained with no gaps in logic.  The activity in question involved having the students write down the sequence of events that are necessary to make a peanut butter and jelly sandwich.  (Watch a [Fun music video non sequitur](https://www.youtube.com/watch?v=4jBDnYE1WjI).)  Then an outside actor "PB&J guy" comes in and does exactly what the students have written, which is not at all what the students meant.  This is an exercise in getting students to think carefully and write precisely.  And then in class it is possible to refer to gaps in logic in a very handy way by referencing "PB&J guy" throughout the semester.  Unfortunately I can't find the original post; if anyone finds it, I will update this post.  ([Here is a nice handout about such an activity](http://static.zerorobotics.mit.edu/docs/team-activities/ProgrammingPeanutButterAndJelly.pdf).)

I'm trying to figure out how to incorporate more creative writing into my own mathematics classroom.  Would that mean writing a paper from the point of a view of a mathematician so that the theorem they just proved is understood more in context?  I have already had students research mathematicians and write papers or edit Wikipedia on them, but this would take that to another level. Would that mean writing a play or story that had as its basis some mathematical theory or computer science algorithm?  (In fact, our class acts out the Gale-Shapley algorithm in Graph Theory.)  Would this involve having the students explain their thought processes when they are writing their proofs or having students submit not just their proofs but also their proof drafts and including a discussion about why they had to change their original reasoning?  I will be able in incorporate one of these ideas next semester in my Math with Mathematica class.  I will make sure to have my students write the thought process they went through to create their mathematical art, so student's aren't just "making art"—they are being thoughtful in the choices they make along the way.

*This blog post is part of the Queens College Teaching Circle blog; it is cross-posted on my personal teaching blog, [Math Razzle](../../index.qmd).*
