---
title: "The Experiential Learning Group at Queens College"
date: 2015-10-21
categories:
  - "teaching"
description: "Abstract: This post is a quick introduction to our college's experiential learning group. What is experiential learning? What happens in a group..."
---

**Abstract:** This post is a quick introduction to our college's experiential learning group.  What is experiential learning?  What happens in a group meeting?

I've been participating in a teaching and learning group at Queens College focused on Experiential Learning since it was founded in 2012 when Grace Davie (QC History) was taking the lead.  This group of like-minded educators spans many disciplines and provides a refreshing sense of community on a commuter campus where people in different departments rarely interact.  While the faculty members participating in the various events changes each time, the value of attending the group is always very high since the self-selecting members inevitably care about teaching.

What is experiential learning?  "Excellent question!" We spent many of our first meetings trying to determine a good working definition for our group.  Should the focus be on social justice work of our students that happens off campus?  Should the focus be on college-sponsored internships where students learn skills ``on the job''? Should the focus be on active learning activities that happen in the classroom where students engage with and experience the material instead of passive non-participation?  We ended up deciding to not decide.  We wanted our group to be an umbrella group that allowed people with disparate interests to come together and share their innovative teaching practices.

At the beginning our group met in multi-day workshops to which were invited outside speakers to discuss teaching pedagogy and mindfulness.  More recently I have been carrying the torch of our Experiential Learning group by organizing and serving as the moderator of lunchtime discussion sessions, sponsored by the [Queens College Center for Teaching and Learning](https://www.qc.cuny.edu/cetll/).  I tend to favor round-table discussions where we each get to bring in ideas from our teaching, and that is the focus of today's lunch, where I have asked participants to prepare a 2-3 minute discourse about something that they tried recently and a self-evaluation of what went well and what could be improved in the future.

The most positive aspect about this format is that we are exposed to many different ideas and we get to see the diversity of techniques that are available and in practice at Queens College.  This helps to give a sense that we are a college where good teaching by our peers is happening and is valued. The most negative part about this format is that for everyone to talk, people get at most five minutes, so it is impossible to get into the nitty gritty details about the module's implementation or give constructive feedback to the presenter, or have a deeper philosophical discussion about the module.  These points were better addressed under the multi-day workshop format, which takes much more preparation by the organizers.

Today's session has an additional undercurrent of supporting the administration's need to collect information about experiential learning that happens through Queens College to comply with the City University of New York's task force, required by a new New York State law to increase experiential or applied learning opportunities for undergraduates.  One personal goal of mine will be to have people contribute their experiential learning modules to the collection effort.

I'm sure that today will be as invigorating as always!  We have another lunch scheduled for December 2, 2015.  If you are around and would like to participate, make sure to join us!  You can email me at chanusa@qc.cuny.edu to be added to my email distribution list about Experiential Learning at Queens College.

*This is the third blog post that I am writing as part of the Queens College Teaching Circle blog; it is cross-posted on my personal teaching blog, [Math Razzle](../../index.qmd).*
