---
title: "Announcing the Circular Teaching Squad"
date: 2016-02-24
categories:
  - "teaching"
description: "Abstract: I discuss the rationale for changing the name of our lunch discussion group. Join us March..."
---

**Abstract:** I discuss the rationale for changing the name of our lunch discussion group.  Join us March 22nd!

For a couple years now I have been moderating lunch discussions about teaching and learning on campus here at Queens College.  I had been doing so under the guise of the [Experiential Learning Group](../2015-10-21-the-experiential-learning-group-at-queens/index.qmd) started back in 2012.  After our last lunch, my friend and kindred spirit striving for excellence in teaching Nathalia Holtzman came up to me and suggested that I move away from its association with the defunct Experiential Learning group.

I was especially swayed by the argument that the discussions we have been having about teaching and learning are much broader than "experiential learning", and perhaps that misnomer was keeping other faculty away who might want to participate in a more general discussion about teaching and learning but were either less interested in experiential learning, or unsure of what this buzzword entails.  This set in motion the idea to change the name of the group.

The name I chose for the group is the **Circular Teaching Squad**.  I like this name for multiple reasons.  First, it is unusual, and would make people pause, question, and consider it, if only for a small while.  Second, it is playful, which is a quality I very much enjoy.  Third, it can be easily shortened to "The Teaching Squad" or just "The Squad".  Fourth, isn't **SQUAD** an ***amazing*** word?  It even has a Q in it, just like Queens!  Fifth, it conveys the idea of a "Teaching Circle", where we share ideas as equals.

Last, what truly inspired me to choose the name is the concept of a [Circular Firing Squad](https://en.wiktionary.org/wiki/circular_firing_squad), in which a group of people (often political candidates) attack each other, often weakening themselves so much that they lose the bigger fight.  Instead of weakening each other, our discussions involve shooting ideas about teaching and learning into a circle of peers who teach diverse subjects, transmitting practical knowledge and strengthening our bonds as educators at this public university.

The Circular Teaching Squad will meet from 12-2 on Tuesday, March 22 in the President's Conference Room #1 in the Queens College Library.  (Stay the whole time or drop in informally!)  The topic of discussion will be about the ways in which we teach students how to learn.  Should we teach these ideas in a more explicit way?  In what ways do we teach students how to take ownership of their learning? While the is the first meeting under the new name, it will continue our tradition of invigorating the discussion of teaching and learning on campus!  If you're in the neighborhood, we'd love to see you there!

*This blog post is part of the Queens College Teaching Circle blog; it is cross-posted on my personal teaching blog, [Math Razzle](../../index.qmd).*
