---
title: "Announcing The MathZorro Podcast"
author: "Christopher R. H. Hanusa"
date: 2015-07-16
categories:
  - "teaching"
  - "math"
description: "Abstract: In Fall 2014, I recorded podcasts with my Combinatorics students and they are now ready for consumption. You can read descriptions of the..."
---

**Abstract:** In Fall 2014, I recorded podcasts with my Combinatorics students and they are now ready for consumption.  You can read [descriptions of the episodes](https://hanusa.xyz/podcasts.html), or subscribe on [iTunes](https://hanusa.xyz/podcasts.html) or [Stitcher](https://hanusa.xyz/podcasts.html).

One of my core teaching philosophies is that students are the most motivated to learn and internalize the concepts they are learning best when they are invested in a project.  (This would be my framing of the idea of *experiential learning*.)  All my upper-level classes involve some project-based component.  In my Combinatorics class, I supervise parallel research projects, where students work either by themselves or with a partner to investigate a counting question they have found somewhere in the real world.  For example our most recent crop of projects included analyzing the New York Knicks' basketball shooting possibilities, counting ways to place chess pieces on a chessboard, and investigating the collection of collectable cards (such as Pokemon or baseball cards).

I like to end the semester with a poster session; the students complete their research, determine the main results of their work, and organize this information on poster board.  The posters are all set up in a room and students share their work with their peers informally and more formally in a presentation to the class.  It is a fantastic capstone to the semester because it is an informal setting in which the student get to show off their hard work.  Moreover, the students get to see all the techniques that they learned in the class applied to a wide variety of topics.  ([Here is a screencast discussing the poster session](https://plus.google.com/+ChristopherHanusa/posts/Rv6CQZrKnpA).)

In Fall 2014, I realized that there was a part of the project's deliverables that I wanted to improve.  I really like the poster session, but I also find it important for the students to compile a summary of their work where they address the most important take-away messages from their work.  In previous incarnations of the course, the students would write a page-long summary, I would skim it, and ... it would go no further.  Since the poster session was the last meeting of the semester, students wouldn't get any feedback and they wouldn't think more deeply about it.

I wanted to change the "throwaway" aspect of this summary, so I decided to move the poster session a bit earlier in the semester, and during Finals Week I would invite my students into my office to record an interview with me about their research.  After editing, this would be published as a podcast.  I provided my students with the same basic thought exercises that I had previously had them write about, but instead of summarizing the important points in written form, the students recorded answers to these questions orally.

This was excellent in multiple ways.   First, the students had invested so much time in the work over the semester---they had honed their projects and received feedback and guidance in class and in office hours.  Moreover, they had already had to think about organizing their information to be displayed on a poster and to be presented to the class at the poster session.  In effect, this recording session served as a time for project debriefing---the students had one final chance to share their excitement for their project and the process with me.

What I really value about these podcasts is that my students' research can be shared with a much larger audience.  I always got to the end of the semester and felt like more people should see the amazing work that my students had done.  Sure, a few non-student peers had always attended, as had our very supportive department chair and some fellow faculty members (math and non-math), but I knew that the quality of much of my students' work was quite good and should be better preserved.  I had always posted image galleries of the posters online; but now with a podcast, the students' work is able to be preserved in multiple media formats.

I am happy to announce that as of this month, the fruits of the my students' labor are available for listening as a podcast: [The MathZorro Podcast](https://hanusa.xyz/podcasts.html).  Follow that link to see detailed descriptions of all 15 episodes.  Here are also links to subscribe on [iTunes](https://hanusa.xyz/podcasts.html) or [Stitcher](https://hanusa.xyz/podcasts.html).

The podcasts turned out great.  You will be able to hear the enthusiasm my students had for their work, and the variety of questions that they addressed.  I had two students who were recent immigrants and they included a message in Chinese to share with family in China.  One special feature of each podcast was when I asked my students to share a favorite number that appeared in their research.  It was fun to hear what they chose and why---some gave a final answer to their question, some gave a number that seemed to appear multiple times, and some found a way to avoid giving one answer to this question.  (This feature was inspired by two podcasts I like: the Marketplace Tech Report and the Slate Money Podcast)

I am proud of the work my students did, and I am especially happy to be able to produce more mathematical content to share with the world.  If you are looking for one episode to try out, I would suggest listening to one of the first six episodes (Card Collecting through Basketball).  If you are not a mathematician, perhaps a nice first episode would be #5 Lattice Paths?

I would love to record some more podcasts with mathematicians of all stripes.  If you'd be interested in trying it out, [drop me a line](https://hanusa.xyz/contact.html)!

*This is the second blog post that I am writing as part of the Queens College Teaching Circle blog; it is cross-posted on my personal teaching blog, [Math Razzle](../../index.qmd).*
