---
title: "New Year, New Site"
date: "2026-01-01"
categories: [misc,meta]
toc: true
description: "I've renewed my website for 2026, including a refreshed feel and an integrated blog. How did it happen and what can you expect from the update?"
author:
  - name: 
      given: Christopher R. H. 
      family: Hanusa
citation: true
appendix-cite-as: display
lightbox: auto  # allows images to be put into lightbox mode.
# Update the below to integrate bluesky and mathstodon comments on this post.
# filters:
#   - open-social-comments
# mastodon_comments:
#   user: "mathzorro"
#   host: "mathstodon.xyz"
#   toot_id: "*****"
# bluesky_comments:
#   post_uri: "https://bsky.app/profile/mathzorro.bsky.social/post/*****"
---

## Welcome!

Welcome to hanusa.xyz, the webpage of Christopher R. H. Hanusa, professor of mathematics at [Queens College](https://www.qc.cuny.edu) of the City University of New York.

In 2025, Queens College decided to transition all its webpages away from college infrastructure. So I set up hanusa.xyz to be my index.html away from home. I thought that the xyz domain would be suitable since it evokes the $(x,y,z)$ coordinate system, my mathematical research is in the combinatorics of high dimensional geometry, and the [mathematical art](https://christopherhanusa.com) and [mathematical jewelry](https://hanusadesign.com) that I design is designed in the computer and made physical through a 3D printing process.

## The Vision

In late 2025 and early 2026, I took the time to redevelop the site to be more reflective of the breadth of the work that I do in my job, and allow for updating the website through a blog interface, as you're reading right now. I've gained skills in conveying ideas through regular updates as I took on my role as the Faculty Liaison for Evaluation and Assessment and built communication infrastructure to keep the campus informed as it undergoes its regular reaffirmation of accreditation process.

My goal in writing is to provide additional context for the work that I do as a professor, to increase transparency about all the facets of the job, and share the good work that happens amongst my collaborators and colleagues.

## Coding the Site

The site is hosted on Github Pages, and was developed with the help of Google Gemini. I used Visual Studio Code to code the webpages.

The blog feature is built using Quarto, which I developed using the github interface.

Quarto has a number of nice built-in features, like $\LaTeX$ code: $$\sum_{i=1}^\infty \textup{Wow}_i!,$$

:::{.callout-note}
fun callouts like these,
:::

RSS feeds that allow for direct integration with the webpages on [hanusa.xyz](https://hanusa.xyz).

and a way to streamline the citation of these posts. (See below.)

Quarto also has nice extensions, including [lightbox](https://github.com/quarto-ext/lightbox) to allow users to zoom in on images and and [open social comments](https://andreasthinks.me/posts/quarto_comments/open-social.html), which will allow for comments that get posted as replies to my posts on Bluesky (and Mastodon if there's interest).

I'm excited to add this additional flexibility and functionality into my website. Thanks for following along.
