---
title: "Why blog about mathematics?"
author:
  - name:
      given: Christopher R. H.
      family: Hanusa
date: 2013-08-09
categories:
  - "math"
  - "misc"
description: "An important part of being a researcher is conveying what you learn to others. The way mathematicians convey their results to colleagues is to write..."
---

Hi everyone!

An important part of being a researcher is conveying what you learn to others.  The way mathematicians convey their results to colleagues is to write articles, which nowadays are posted on the [arXiv](http://arxiv.org/list/math/recent) and submitted for publication in journals.  In a journal, an article is ideally peer-reviewed to check for correctness and then published once any issues are corrected.

This system works well for mathematicians to convey topics to other mathematicians who have a similar background of knowledge as themselves.  However, the size of the audience for these specialized journal articles is limited.  For example, if I try to talk to other research mathematicians *in my own department* about our recent results, this is a non-trivial undertaking.

I think that it is our duty as mathematicians to share our understanding with as wide an audience as possible, and I think that creating and maintaining a blog is one good way to try to explain my research to a wider audience.  I have been hoping to do this for a while and I figured that I would start with my most recent joint work on [simultaneous core partitions](http://arxiv.org/abs/1308.0572) with Brant Jones and [Drew Armstrong](https://www.math.miami.edu/~armstrong/).  I may just have gotten [a round tuit](https://www.google.com/search?q=a+round+tuit&tbm=isch).

I realize that even when I try to convey these ideas, it will not make sense to everyone.  But I expect this to be a learning experience for me as well as for you.  If you have any questions about the topics involved, leave a comment and I will try to answer your questions by providing external links or writing additional blog posts.

I would encourage other researchers to broaden their audiences as well, be it in research mathematics, mathematics education, or any other field.  I think it is good for the researcher to try to convey their ideas to a wider field, and good for the public to see what it is that we do.  I see this as part of a larger project, similar to [Dana Ernst](https://danaernst.com/)'s [recent post](https://plus.google.com/u/0/107135522210834007871/posts/dhaPmhY8F8J) about making a "Science Gist" for mathematics.

Onward and upward!
